ok

diff --git a/frappe/erpnext/templates/job-backup.yaml b/frappe/erpnext/templates/job-backup.yaml
--- a/frappe/erpnext/templates/job-backup.yaml
+++ b/frappe/erpnext/templates/job-backup.yaml
@@ -26,61 +26,72 @@ spec:
         imagePullPolicy: {{ .Values.image.pullPolicy }}
         command: ["bash", "-c"]
         args:
-        - >
-            bench --site=$(SITE_NAME)
-          {{- if .Values.jobs.backup.withFiles }}
-            backup --with-files;
-          {{- else }}
-            backup;
-          {{- end }}
-          {{- if .Values.jobs.backup.push.enabled }}
-            echo "Nombre del Sitio: $SITE_NAME"
+          - >
+              bench --site=$(SITE_NAME)
+            {{- if .Values.jobs.backup.withFiles }}
+              backup --with-files;
+            {{- else }}
+              backup;
+            {{- end }}
+            {{- if .Values.jobs.backup.push.enabled }}
+              echo "Nombre del Sitio: $SITE_NAME"
 
-            # Directorio de backups
-            BACKUP_DIR=$("/home/frappe/frappe-bench/sites/$SITE_NAME/private/backups/")
+              # Imprimir el directorio actual
+              echo "Directorio actual:"
+              pwd
+              echo "Contenido del directorio actual:"
+              ls -la
 
-            # Verificar que el directorio de backups existe
-            if [ ! -d "$BACKUP_DIR" ]; then
-              echo "El directorio de backups no existe: $BACKUP_DIR" >&2
-              exit 1
-            fi
+              # Directorio de backups (ajustar según la salida anterior)
+              BACKUP_DIR="./erp.mabecenter.org/private/backups/"
 
-            # Iterar sobre cada archivo de respaldo con extensión .gz o .json
-            for BACKUP_FILE in $(ls "$BACKUP_DIR" | grep -E '\.(gz|json)$'); do
-              echo "Procesando archivo de respaldo: $BACKUP_FILE"
-
-              # Extraer el prefijo de la fecha y hora del nombre del archivo para usarlo como carpeta
-              DESTINATION_FOLDER=$(echo "$BACKUP_FILE" | cut -d'-' -f1)
-              echo "Carpeta de Destino: $DESTINATION_FOLDER"
-
-              # Construir el path completo dentro del bucket
-              OBJECT_KEY="$DESTINATION_FOLDER/$BACKUP_FILE"
-              echo "Objeto en el Bucket: $OBJECT_KEY"
-
-              # Crear la firma HMAC para la solicitud PUT
-              STRING_TO_SIGN="PUT\n\napplication/octet-stream\n\n/$OBJECT_KEY"
-              SIGNATURE=$(echo -n "$STRING_TO_SIGN" | openssl sha1 -hmac "$SECRET_KEY" -binary | openssl base64)
-
-              # Obtener la fecha actual en el formato requerido por AWS S3
-              DATE=$(date -R)
-              echo "Fecha: $DATE"
-
-              # Realizar la subida del archivo utilizando curl
-              curl -v -X PUT "$BACKUP_PATH/$OBJECT_KEY" \
-                -H "Content-Type: application/octet-stream" \
-                -H "Authorization: AWS $ACCESS_KEY:$SIGNATURE" \
-                -H "Date: $DATE" \
-                --upload-file "$BACKUP_DIR/$BACKUP_FILE"
-
-              if [ $? -eq 0 ]; then
-                echo "Subida exitosa de $BACKUP_FILE"
-              else
-                echo "Error al subir $BACKUP_FILE" >&2
+              # Verificar que el directorio de backups existe
+              if [ ! -d "$BACKUP_DIR" ]; then
+                echo "El directorio de backups no existe: $BACKUP_DIR" >&2
+                exit 1
               fi
-            done
 
-            echo "¡Subida de todos los archivos completada!"
-          {{- end }}
+              # Listar los archivos en el directorio de backups
+              echo "Contenido del directorio de backups:"
+              ls -la "$BACKUP_DIR"
+
+              # Iterar sobre cada archivo de respaldo con extensión .gz o .json
+              for BACKUP_FILE in $(ls "$BACKUP_DIR" | grep -E '\.(gz|json)$'); do
+                echo "Procesando archivo de respaldo: $BACKUP_FILE"
+
+                # Extraer el prefijo de la fecha y hora del nombre del archivo para usarlo como carpeta
+                DESTINATION_FOLDER=$(echo "$BACKUP_FILE" | cut -d'-' -f1)
+                echo "Carpeta de Destino: $DESTINATION_FOLDER"
+
+                # Construir el path completo dentro del bucket
+                OBJECT_KEY="$DESTINATION_FOLDER/$BACKUP_FILE"
+                echo "Objeto en el Bucket: $OBJECT_KEY"
+
+                # Obtener la fecha actual en el formato requerido por AWS S3
+                DATE=$(date -R)
+                echo "Fecha: $DATE"
+
+                # Crear la firma HMAC para la solicitud PUT
+                STRING_TO_SIGN="PUT\n\napplication/octet-stream\n$DATE\n/$OBJECT_KEY"
+                SIGNATURE=$(echo -en "$STRING_TO_SIGN" | openssl sha1 -hmac "$SECRET_KEY" -binary | openssl base64)
+
+                # Realizar la subida del archivo utilizando curl
+                curl -v -X PUT "$BACKUP_PATH/$OBJECT_KEY" \
+                  -H "Content-Type: application/octet-stream" \
+                  -H "Authorization: AWS $ACCESS_KEY:$SIGNATURE" \
+                  -H "Date: $DATE" \
+                  --upload-file "$BACKUP_DIR/$BACKUP_FILE"
+
+                if [ $? -eq 0 ]; then
+                  echo "Subida exitosa de $BACKUP_FILE"
+                else
+                  echo "Error al subir $BACKUP_FILE" >&2
+                fi
+              done
+
+              echo "¡Subida de todos los archivos completada!"
+
+            {{- end }}
         env:
           - name: "SITE_NAME"
             value: "{{ .Values.jobs.backup.siteName }}"
